Handle "setup" migration status
Setup status was introduced in qemu's rdma branch.

commit 9ca54b9e3a0b753c5b7fad274f98d9de61bf7c4a
Author: Michael R. Hines <mrhines@us.ibm.com>
Date:   Tue Jun 18 15:46:43 2013 -0400

    time setup phase instead of specific pinning phase

Not handling it will sometimes lead to the folllowing eror

    error: internal error unexpected migration status in setup

and any further attempt to migrate will lead to

    error: internal error unable to execute QEMU command 'migrate': There's a migration process in progress